const resObj = [
  {
    info: {
      id: "615655",
      name: "Subway",
      cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
      locality: "Advant Mall",
      areaName: "Sector 144",
      costForTwo: "₹350 for two",
      cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
      avgRating: 3.7,
    },
  },
  {
    info: {
      id: "570254",
      name: "Burger King",
      cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
      locality: "sector 129",
      areaName: "sector 129",
      costForTwo: "₹350 for two",
      cuisines: ["American"],
      avgRating: 4.1,
    },
  },
  {
    info: {
      id: "702769",
      name: "La Pino'z Pizza",
      cloudinaryImageId: "5fe4444a065b60c4fe39ef975222c12b",
      locality: "World One",
      areaName: "Sector 90",
      costForTwo: "₹400 for two",
      cuisines: [
        "Pizzas",
        "Pastas",
        "Beverages",
        "Fast Food",
        "Italian",
        "Desserts",
      ],
      avgRating: 3.7,
    },
  },
  {
    info: {
      id: "247713",
      name: "Wake Up Sid",
      cloudinaryImageId: "tbikwlzi1hhuip4mvvrj",
      locality: "Gardenia Gateway",
      areaName: "Sector 72",
      costForTwo: "₹400 for two",
      cuisines: [
        "North Indian",
        "Chinese",
        "Continental",
        "Italian",
        "Snacks",
        "Beverages",
        "Indian",
        "Biryani",
        "Mughlai",
        "Mexican",
        "Seafood",
        "Punjabi",
        "Tandoor",
        "Salads",
        "Tibetan",
      ],
      avgRating: 4,
    },
  },
  {
    info: {
      id: "562781",
      name: "The Burger Club",
      cloudinaryImageId: "h4ppdoav5fdi0gsswpab",
      locality: "Ch Nitin Khari Marg",
      areaName: "Sector 141",
      costForTwo: "₹250 for two",
      cuisines: ["American", "Desserts", "Beverages"],
      avgRating: 3.8,
    },
  },
  {
    info: {
      id: "684915",
      name: "Crusty Culture- Artisan Pizzas",
      cloudinaryImageId: "2bb57783501a5b7ac4dbf523c4e5ab11",
      locality: "Village Hazipur",
      areaName: "Noida Expressway",
      costForTwo: "₹500 for two",
      cuisines: ["Italian"],
      avgRating: 4.2,
    },
  },
  {
    info: {
      id: "142009",
      name: "Burger Singh (Big Punjabi Burgers)",
      cloudinaryImageId: "akfdak4ssaatkz24epnk",
      locality: "Ajnara Daffodil",
      areaName: "Sector 135",
      costForTwo: "₹300 for two",
      cuisines: [
        "Snacks",
        "Fast Food",
        "Indian",
        "American",
        "Beverages",
        "Desserts",
        "Mughlai",
        "North Indian",
        "Biryani",
      ],
      avgRating: 4.2,
    },
  },
  {
    info: {
      id: "356221",
      name: "KFC",
      cloudinaryImageId: "56c9ab92bd79745fd152a30fa2525426",
      locality: "Hazipur",
      areaName: "Hajipur",
      costForTwo: "₹450 for two",
      cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
      avgRating: 4.1,
    },
  },
  {
    info: {
      id: "628921",
      name: "Kathi Express",
      cloudinaryImageId: "7d286f377663fa2022631fd9c4674528",
      locality: "Assotech Business Cressterra",
      areaName: "Sector 135",
      costForTwo: "₹300 for two",
      cuisines: ["Snacks", "Lebanese", "Beverages", "Indian"],
      avgRating: 4.1,
    },
  },
  {
    info: {
      id: "744470",
      name: "Chinese Hotspot",
      cloudinaryImageId: "b14cd9fc40129fcfb97aa7e621719d07",
      locality: "Gautam Buddha Nagar",
      areaName: "Sector 50",
      costForTwo: "₹400 for two",
      cuisines: ["Chinese", "Indian", "Rolls & Wraps", "Snacks", "Beverages"],
      avgRating: 4.5,
    },
  },
  {
    info: {
      id: "498975",
      name: "Chinese Hunger",
      cloudinaryImageId: "all1uctffk1q6mpwfmtl",
      locality: "Hazipur",
      areaName: "Hajipur",
      costForTwo: "₹300 for two",
      cuisines: ["Chinese"],
      avgRating: 4.2,
    },
  },
  {
    info: {
      id: "172540",
      name: "Tandoori kitchen",
      cloudinaryImageId: "v0yvnk9lj6nhvw1avgzh",
      locality: "C Block",
      areaName: "Sector 71",
      costForTwo: "₹99 for two",
      cuisines: ["North Indian", "Chinese", "Tandoor"],
      avgRating: 3.7,
    },
  },
  {
    info: {
      id: "750654",
      name: "Street Bistro - Pure Desi Dhaba",
      cloudinaryImageId: "a72b708d98585d796e930160abafb308",
      locality: "Gautam Buddha Nagar",
      areaName: "Noida Expressway",
      costForTwo: "₹500 for two",
      cuisines: ["North Indian", "Biryani", "Mughlai", "Chinese", "Kebabs"],
      avgRating: 5,
    },
  },
  {
    info: {
      id: "142001",
      name: "Salad Days",
      cloudinaryImageId: "cfa1123ebf17413dc7d0a80c7361fab3",
      locality: "Golf Course",
      areaName: "Sector 45",
      costForTwo: "₹500 for two",
      cuisines: ["Salads"],
      avgRating: 4.5,
    },
  },
  {
    info: {
      id: "738170",
      name: "Sashmicks Bakery",
      cloudinaryImageId: "31e52bcbebacbc8f5b7352b52beb709d",
      locality: "Shahdra",
      areaName: "Noida Expressway",
      costForTwo: "₹500 for two",
      cuisines: ["Bakery", "Desserts"],
      avgRating: 4.4,
    },
  },
  {
    info: {
      id: "603973",
      name: "Fire House Pizza",
      cloudinaryImageId: "lj4dr56pkm2ri1boulp8",
      locality: "Sector 75",
      areaName: "Sector 75",
      costForTwo: "₹200 for two",
      cuisines: [
        "Pizzas",
        "Pastas",
        "Beverages",
        "Italian",
        "Fast Food",
        "Snacks",
      ],
      avgRating: 4,
    },
  },
];

export default resObj;
